### PR TITLE
Add Pinterest domains

### PR DESCRIPTION
**Pull request by ukutaht**
Screenshot from 2022-03-04 15-36-06

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by ukutaht** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @ukutaht has signed the Contributor License Agreement. Thanks so much.

**Comment by lukabirsa** [comment]
I see that there were no merges since 2020. Is this package still actively supported?

**Comment by benjben** [comment]
Hi @lukabirsa ,

Indeed we've not done a great job merging the PRs, but this is still used in production.

Enrich (one of the main components of Snowplow pipelines) uses [scala-referer-parser](https://github.com/snowplow-referer-parser/scala-referer-parser) for [referer parser enrichment](https://docs.snowplow.io/docs/enriching-your-data/available-enrichments/referrer-parser-enrichment/), which is based on this database.

Let me merge the PRs.

**Comment by benjben** [comment]
Thanks @ukutaht for the PR ! Sorry for taking so long to merge it.

**Pull request merged**
