### PR TITLE
Add support for Core Digital's Paid lowermybills.com product

### PR DESCRIPTION
**Pull request by ramin**
Adds support for paid referals from the lowermybills.com product by [Core Digital](http://www.coredigital.com/).

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by ramin** [comment]
i signed it!

**Comment by snowplowcla** [comment]
Confirmed! @ramin has signed the Individual Contributor License Agreement. Thanks so much

**Comment by ramin** [comment]
any chance of a merge?

**Comment by BenFradet** [comment]
Sorry I was on holidays when the pull request was opened, I'll have a look :+1:

**Comment by ramin** [comment]
Awesome thanks!!!!

**Comment by ramin** [comment]
it looks like this change never made it to the live database, referenced here https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yml

when do new changes go out?

**Comment by alexanderdean** [comment]
Hi @ramin - there's no formal process currenly (and the referer-parser implementations mostly don't support the external file yet).

**Pull request merged**
