### PR TITLE
Duplicate domains check in Parser

### PR DESCRIPTION
**Pull request by blazy2k9**
1. Fixed the duplicate domains check while parsing the referers.yml file
2. Deleted all duplicate/Updated domains in referers.yml

Tested Locally.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @blazy2k9 ! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by blazy2k9** [comment]
I just signed the CLA.

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by alexanderdean** [comment]
Cherry-picked data commit into [data-jun-2017](/snowplow/referer-parser/tree/data-jun-2017), leaving open for Java library commit...

**Comment by BenFradet** [comment]
We've migrated the java codebase to https://github.com/snowplow-referer-parser/java-referer-parser, feel free to open a pr there :+1:

**Pull request closed without merging**
