### PR TITLE
update referers.yml

### PR DESCRIPTION
**Pull request by seanhall**

### CODE REVIEW

**Comment by seanhall** [comment]
The most frequent new referrer we're seeing is com.google.android.googlequicksearchbox, which we assume to be the search box on most Android phone home screens.  It doesn't supply a query parameter unfortunately but I've added it to the end of the Google search domain list.

**Comment by alexanderdean** [comment]
Thanks @seanhall - this looks great!

**Comment by snowplowcla** [comment]
@seanhall has signed the Software Grant and Corporate Contributor License Agreement. Thanks so much

**Comment by seanhall** [comment]
What's the timeline for merge and deployment?  Thanks!

**Comment by BenFradet** [comment]
@seanhall unfortunately, we don't have a clear timeline for the next release at the moment, we'll keep you updated though :+1:

**Comment by seanhall** [comment]
Ok until then if I host my own assets (change the path in my EMR ETL Runner config.yml to my own bucket copy of s3://snowplow-hosted-assets) I assume the enrichment will read from my local copy of referers-latest.yml?

**Comment by alexanderdean** [comment]
You'd have to splice your updated referers file into the Spark Enrich fatjar, and then host that in your own hosted assets bucket.

**Comment by seanhall** [comment]
We are still on Hadoop Enrich, I am looking for a hard coded reference to s3://snowplow-hosted-assets but haven't found one to update yet.

**Comment by alexanderdean** [comment]
Hey @seanhall - you need to direct any Snowplow support questions to our community forums, https://discourse.snowplowanalytics.com/

**Comment by seanhall** [comment]
I will do that.  I understand that we're not running the latest, but we are running what's long been mature and stable, so I'd request that if the community can't help, you can still support while my PR remains shelved.  Thanks gents.

**Comment by BenFradet** [comment]
@seanhall could you rebase against develop so we can merge it? Thanks :+1:

**Comment by GianniObiglio** [comment]
Can we update the referers after 2.5 years ? :)

**Comment by alexanderdean** [comment]
We are working on rebooting this project now, @GianniObiglio

**Comment by GianniObiglio** [comment]
@alexanderdean Good news ! i am an active user of this project :)

**Comment by brianjlowry** [comment]
It's July of 2019. Is this dead?

**Comment by BenFradet** [comment]
no, we're putting in place a process that will publish the referer db monthly.

**Pull request closed without merging**
