### PR TITLE
fix broken link to referers-latest.yaml

### PR DESCRIPTION
**Pull request by mleuthold**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by benjben** [comment]
Hi @mleuthold , thank you for the fix. Could sign our [CLA](https://docs.google.com/forms/d/e/1FAIpQLSd89YTDQ1XpTZbj3LpOkquV_h1Y8k9ay3iFbJsZsJrz18I23Q/viewform) please so that we can merge the PR?

**Comment by mleuthold** [comment]
Hi @benjben, I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @mleuthold has signed the Contributor License Agreement. Thanks so much.

**Comment by benjben** [comment]
Great, thank you for the contribution!

**Pull request merged**
