### PR TITLE
Bump list of known sources with some popular domains.

### PR DESCRIPTION
**Pull request by secoint**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by BenFradet** [comment]
Thanks @secoint , I'll have a look on Monday :+1: , feel free to sign the cla in the meantime

**Comment by secoint** [comment]
Hi @BenFradet ,
I've signed a CLA.

Thanks!

**Comment by snowplowcla** [comment]
Confirmed! @secoint has signed the Individual Contributor License Agreement. Thanks so much

**Comment by BenFradet** [comment]
Thanks, merged!

**Pull request merged**
