### PR TITLE
[Referer] Add new search referer Lilo

### PR DESCRIPTION
**Pull request by abdullah7**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by abdullah7** [comment]
> Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.
> 
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I signed it

**Comment by snowplowcla** [comment]
Confirmed! @abdullah7 has signed the Contributor License Agreement. Thanks so much.

**Comment by mirkoprescha** [comment]
Hi,
is there anything still missing to merge this change?
thank you

**Comment by benjben** [comment]
Thanks @abdullah7 for the PR ! Sorry for taking so long to merge it.

**Pull request merged**
